/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    Clock: typeof import('./src/components/Clock.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    FramePlayer: typeof import('./src/components/video/FramePlayer.vue')['default']
    IframePlayer: typeof import('./src/components/video/IframePlayer.vue')['default']
    ImgPlayer: typeof import('./src/components/video/ImgPlayer.vue')['default']
    ModelList: typeof import('./src/components/video/ModelList.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RightSider: typeof import('./src/components/RightSider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubHeader: typeof import('./src/components/SubHeader.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCollapse: typeof import('tdesign-vue-next')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next')['CollapsePanel']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TOption: typeof import('tdesign-vue-next')['Option']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
  }
}
